language: ruby
bundler_args: --without development
rvm:
    - 1.9.3
    - 2.0.0
    - ruby-head
script:
    - "bundle install"
    - "bundle exec rake lint"
    - "bundle exec rake spec SPEC_OPTS='--format documentation'"
env:
    - PUPPET_VERSION=3.7.2
    - PUPPET_VERSION=4.0.0
matrix:
    exclude:
        - rvm: ruby-head
    allow_failures:
        - rvm: ruby-head
gemfile: Gemfile
# build only these
branches:
    only:
        - master
        - develop
